### ISSUE TITLE
FEATURE: Update Login button to reflect new UI

### ISSUE THREAD

**Issue by KevinGallaccio** [CodersCampus/cp#452]
Updated CSS for Login button:

```CSS
.ui-button {
    display: flex;
    padding: 8px 16px;
    justify-content: center;
    align-items: center;
    gap: 10px;
    border-radius: 20px;
    border: none;
    background: var(--primary);
    box-shadow: 0px 6px 30px rgba(0, 0, 0, 0.12);
    color: var(--background-accent);
    font-family: Poppins, sans-serif;
    font-size: 14px;
    font-style: normal;
    font-weight: 300;
    line-height: normal;
    text-decoration: none;
}

.ui-button:hover {
    color: var(--background);
    box-shadow: none;
    opacity: 0.7;
}

.ui-button:active {
    background-color: var(--accent);
    color: var(--background);
    box-shadow: none;
}
```
